version: "3.2"
services:
  flask:
    network_mode: "host"
    build: .
    restart: always
    environment:
      - APP_NAME=flask
    expose:
      - 8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/home/myuser
  nginx:
    network_mode: "host"
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"